version: '3.1'

services:
  service_mongo:
    container_name: service-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: MfQq>E!5b&nBQ5:^
    ports:
      - "27017:27017"

  car-service-app:
    container_name: car-service-app
    image: car-service-app
    build:
      context: ./
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - service_mongo
  car-service-nginx:
    container_name: car-service-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - car-service-app